### ISSUE TITLE
Project Directory is displayed as Project Title

### ISSUE THREAD

**Issue by radzhiv25** [JammUtkarsh/pms#1]
## Current Behaviour

<img width="324" alt="image" src="https://github.com/JammUtkarsh/pms/assets/84130482/1dfac28e-fbcc-4ff5-bff2-5b85ac709e4f">

## Expected Output
Display project title as anything after last `\`

In my case, project title should be `python`

**Comment by jammutkarsh** [comment]
Hello @radzhiv25,

Can you try to re-installing the binary with `go install github.com/JammUtkarsh/pms@latest` and run `pms` to check if it fixes this issue?
