### ISSUE TITLE
bug: the subcommand `add` creates duplicate entries in TUI.

### ISSUE THREAD

**Issue by jammutkarsh** [JammUtkarsh/pms#7]
When the subcommand `add` is run multiple times on the same directory(same absolute path).
It creates multiple entries of it in TUI.

![pms add subcmd](https://github.com/JammUtkarsh/pms/assets/78140690/fb0e9d36-1d93-4ef6-8bbe-91e6e6eaa3a9)

**Comment by sidkhuntia** [comment]
Can i work on it ?

**Comment by jammutkarsh** [comment]
@sidkhuntia you can definitely send a PR to resolve this issue.

Concerned LOC: [cmd/add.go:25](https://github.com/JammUtkarsh/pms/blob/main/cmd/add.go#L25).

If you need any help feel free to reach out!

**Comment by sidkhuntia** [comment]
What should happen when user tries to add same path? 
Should it tell that "Project Already Exists" or simply dont add it or should i return error

right now i am doing this on https://github.com/JammUtkarsh/pms/blob/08500a6b1e20ebdc13e7a8a941d12bb2411a781c/utils/config.go#L128


```go
	for _, p := range c.Projects {
		if p.ProjectPath == newProject.ProjectPath {
			return nil
		}
	}
```

**Comment by jammutkarsh** [comment]
Hi,

Yes, print something like `error: project already exists` and then `os.Exit(1)`.

One more thing, once you have made the final changes, use `go install .` and record the changed in action as gif and post it in the PR.

[VHS](https://github.com/charmbracelet/vhs) is a great tool to record CLI apps but feel free to use anything you like!

**Comment by jammutkarsh** [comment]
Using the `add` command with relative path creates two bugs:
- add relative path to the db.
![out](https://github.com/JammUtkarsh/pms/assets/78140690/a335d98c-05eb-4ab1-9a80-32bc94a4a388)
- creates duplicate entry.
<img width="1107" alt="Screenshot 2023-11-10 at 18 21 51" src="https://github.com/JammUtkarsh/pms/assets/78140690/874b791a-117e-4f0d-8884-68c5007506ee">

Although deleting one does not affect the other.

**Comment by sidkhuntia** [comment]
My bad, couldnt take into account this case, will work on it and try to find some solution. Thanks for pointing out

**Comment by jammutkarsh** [comment]
No issues, even I didn't know about this until now.

## Implementation

With respect to implementation details about this. We can create a single `func pathSeparator(path string) string` for path resolution and write a unit test for the same.

Also the path resolution will be with respect to executable's `pwd`. 

NOTE: We have to address two platform:
1. **Linux/Unix/Mac**
2. **Windows**

Go provides [`os.PathSeparator`](http://golang.org/pkg/os) which solves our single function, multi-platform issue. [more](https://stackoverflow.com/questions/9371031/how-do-i-create-crossplatform-file-paths-in-go)

## Testing

I am a little sceptical about testing via simple strings, since it won't really translate to real world scenarios.

The binary for linux, won't test for windows' test cases and vise versa.
At first, I thought, we could simply create container for both Windows and Linux but just like test cases, they [can't run on each other](https://stackoverflow.com/questions/42158596/can-windows-containers-be-hosted-on-linux).

So, the obvious choice would be to simply create two _functions with build flags_ or _test files with platform suffix_. I am not sure about the first one case, since I don't have a windows machine. But that works, we should go with that.

Then, we can test individually and improve the function.

If you would like to work to on this extended version, let me know.

_PS: Just putting out as much info/context as possible for effective working._

**Comment by sidkhuntia** [comment]
Yeah I would like to work on it. I just need some time as I have some exams coming up. If that's not an issue then I will work on it.

**Comment by jammutkarsh** [comment]
Sure, also check the updated [comment](https://github.com/JammUtkarsh/pms/issues/7#issuecomment-1806633382) with more added context.

**Comment by sidkhuntia** [comment]
[clean()](https://pkg.go.dev/path/filepath#Clean) function from filepath does the required job I guess. What do you think? I implemented it and it no longer creates duplicate entries for the same dir
